app_home:
    path: /
    defaults: { _controller: AppBundle:Car:list }
edit_car:
    path: /car/{id}
    methods: [GET]
    defaults: { _controller: AppBundle:Car:edit }
submit_edit_car:
    path: /car/{id}
    methods: [POST]
    defaults: { _controller: AppBundle:Car:editSubmit}
create_car:
    path: /create-car
    methods: [GET]
    defaults: { _controller: AppBundle:Car:create }
create_car_submit:
    path: /create-car
    methods: [POST]
    defaults: { _controller: AppBundle:Car:createSubmit }
